version: '3'
services:
  bin-chan:
    build: .
    ports:
      - "1972:1972"
    container_name: bin-chan
    environment:
      - DATABASE_URL=/app/db/db.sqlite3  
    volumes:
      - /var/db:/app/db  
    restart: unless-stopped  