version: '3'
services:
  bin-chan:
    build: .
    ports:
      - "1972:1972"
    container_name: bin-chan
    environment:
      - DATABASE_URL=/var/db/db.sqlite3  
    volumes:
      - ./data:/var/db  
    restart: unless-stopped  